url: https://vlad-velciov.github.io/ocdpro
baseurl: /

# Site settings
title: OCD Processing
email: oana_fluture@yahoo.com
description: "Meeting your data processing needs."

# Team names, titles and social links
people:
- name: Oana Fluture
  pic: 3
  position: Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/oana.fluture

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com
  - title: facebook
    url: http://facebook.com

# Postal address (add as many lines as necessary)
address:
  - line: Garofitei 10
  - line: Timisoara, Romania

# Build settings
markdown: kramdown
permalink: pretty
